---
abstract: 'Catalyst controller for Flash Remoting'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  HTTP::Request: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-FlashRemoting
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.70
  Data::AMF: 0.01001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
